### ISSUE TITLE
ios8.4 上会导致UIAlertController出错

### ISSUE THREAD

**Issue by fishyumiao** [yangli-dev/LYEmptyView#7]
ios 8.4 上测试时，碰到UIAlertController弹出时都会出错。在ios8.2上和ios10上测试正常

**Comment by yangli-dev** [comment]
专门找了8.4的测试机，在使用UIAlertController弹出时并无发现弹出错误。
请尝试使用最新框架解决。如还有此问题，请联系我QQ:944801216

**Comment by GanHuaLin** [comment]
IOS8.4真机上UIAlertController 如果使用了UIAlertActionStyleCancel样式的按钮就出错。
比如有3个Default按钮，1个Cancel按钮就出错。没有Cancel按钮就没问题。
`'NSRangeException', reason: '*** -[__NSArrayM objectAtIndex:]: index 3 beyond bounds [0 .. 2]'`

**Comment by yangli-dev** [comment]
感谢楼上朋友详细的issues，我复现了这个bug。
这个bug在v1.0.1之前存在，在v1.0.2中已经得到解决。
